# Generated by Django 5.2.3 on 2025-06-15 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='experience_detail',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='experience_years',
            field=models.IntegerField(null=True),
        ),
    ]
