# Generated by Django 5.2.3 on 2025-06-15 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_application_experience_detail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='experience_years',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
