# Generated by Django 5.2.3 on 2025-06-15 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_alter_application_experience_years'),
        ('status', '0002_status_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='status.status'),
        ),
    ]
