# Generated by Django 5.2.3 on 2025-06-15 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_alter_application_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='status',
        ),
    ]
